### PR TITLE
Fix minor compilation issue on VS2015

### PR DESCRIPTION
**Pull request by renindustries**
std::to_string cannot convert an std::list to a string.

### CODE REVIEW

**Comment by renindustries** [comment]
This is a minor pull; the dev branch cannot currently compile on any form of visual studio in debug mode, but this is an explicit fix for the new VS 2015 RC. I can't imagine this line working anywhere however; if it does work on linux, it's certainly non-standard.

I attempted to replace it with both as small a line, and as inline of a line as possible; it should convey the same information, and while std::accumulate isn't the best solution, it's the only inline solution I could find. It will put comma's between every include path (and won't put a comma at the end!)

**Comment by warrenseine** [comment]
Actually, it can. Have you looked at `std.hpp`. We override some `std` functions, including `std::string std::to_string(const std::list<T>& list, const std::string& separator)`. We're probably missing a default value for the separator though.

**Comment by renindustries** [comment]
@warrenseine It's not working, though. Are you not properly pulling in `std.hpp`?

**Comment by warrenseine** [comment]
There's a slight desync between our private repo and GitHub. I'll push the update soon.

**Pull request closed without merging**
